
tokenizer:
  name: "google-bert/bert-base-uncased"

architecture:
  n_layers: 4
  d_model: 256
  n_heads: 8
  n_kv_heads: 4
  hidden_size: 1024
  activation: swiglu
  rope: true
  rope_theta: 10000

optimizer:
  type: adamw
  lr: 1e-5
  betas: [0.9, 0.999]
  weight_decay: 0.01

loss:
  type: perplexity

train:
  epochs: 10
  macro_batch_size: 1024
  micro_batch_size: 64
  max_seq_len: 512

device: cuda

data:
  settings:
    prefetch_size: 10000
    cache_dsn: None
    shuffle_buffer: false
    num_workers: 4
  urls:
    - "https://vorox-processed-train-data.s3.us-east-2.amazonaws.com/dclm-baseline-global-shard_01_of_10_local-shard_0_of_10_shard_00000000_processed.tar"
    - "https://vorox-processed-train-data.s3.us-east-2.amazonaws.com/dclm-baseline-global-shard_01_of_10_local-shard_0_of_10_shard_00000001_processed.tar"
    - "https://vorox-processed-train-data.s3.us-east-2.amazonaws.com/dclm-baseline-global-shard_01_of_10_local-shard_0_of_10_shard_00000002_processed.tar"
    - "https://vorox-processed-train-data.s3.us-east-2.amazonaws.com/dclm-baseline-global-shard_01_of_10_local-shard_0_of_10_shard_00000003_processed.tar"
    - "https://vorox-processed-train-data.s3.us-east-2.amazonaws.com/dclm-baseline-global-shard_01_of_10_local-shard_0_of_10_shard_00000004_processed.tar"
    - "https://vorox-processed-train-data.s3.us-east-2.amazonaws.com/dclm-baseline-global-shard_01_of_10_local-shard_0_of_10_shard_00000005_processed.tar"
    - "https://vorox-processed-train-data.s3.us-east-2.amazonaws.com/dclm-baseline-global-shard_01_of_10_local-shard_0_of_10_shard_00000006_processed.tar"
    - "https://vorox-processed-train-data.s3.us-east-2.amazonaws.com/dclm-baseline-global-shard_01_of_10_local-shard_0_of_10_shard_00000007_processed.tar"
    - "https://vorox-processed-train-data.s3.us-east-2.amazonaws.com/dclm-baseline-global-shard_01_of_10_local-shard_0_of_10_shard_00000008_processed.tar"
    - "https://vorox-processed-train-data.s3.us-east-2.amazonaws.com/dclm-baseline-global-shard_01_of_10_local-shard_0_of_10_shard_00000009_processed.tar"
